travis:
  secure:
    BINSTAR_TOKEN: UxV5VrVFobpfxooDFvZsQIR6NWuobM11WrCtbeue90uK98L/H+cQY1jbVVYFKCMZeEaGK+bJNe6L82zb2Si8zDKnrwi5PEK87bIPiGsoA1tPfj8qrVM1ZBDKC91mhSPjwFcqoyl+vtusihXfWTFt4d10IqQENDGVcorFBU1apoV3h4xdw+CBksDs2sUwrDWJT30Ns44vje91O7BhbWYLxr3eH06L0uV3HQZ95CxuB1KAXtRTsAKRvtA+W8xRIinL4novT4pFicSdAkNqEODiXwowJ0tUguPhrQXrMHAqpMhbP9B1uaXXx7Hb6x6LOLRh0dAqX+FobiZUGzXgbF8auKvv2XLgXnvsl24bMvMCFA327Z8WjxNKCN/FMDTTSGMmMX/vjyWPhehzj6r8t1qHrEYfeVxkTs54xh3G/0vwrBSsynzt3u5s6XE/q2PX0H1DWEWitiDURG/chlKQ2Xq7d89QN74uVpBcydSL1kY8KZgDkJE3aBg5NjZhDkmvsjnkmoJxs6nPrU50nPq9xSPK2p1a8ZXEzXreTm5RXOh3IIkecRRBFhFUj8DnHrk5EtIdpB7h8ubhTrQx/HOeZTWE/ZtTQ36z81cBxygdovyHiMwQBtX67TjuR2+E768Tla5deSW9Fm4ltpuigCUAdcklLfWVtUxQuFgr3XzOHLxRa38=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
